language: python
python:
  - "3.6"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

script: nosetests --with-coverage --cover-package=buffpy
after_success:
  coveralls
